name: Test deployment

on:
  pull_request:
    branches:
      - master

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        working-directory: angular
        run: npm ci
      - name: Test build website
        working-directory: angular
        run: npm run build
      - name: Test lint
        working-directory: angular
        run: npm run lint
